apiVersion: v1
kind: Service
metadata:
  name: account-query-svc
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: account-query
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080