apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accounts-ingress
  namespace: {{ .Values.namespace }} # ← Solo si usas Helm
  annotations:
    #konghq.com/websocket: "true"
    #konghq.com/strip-path: "false"
    #konghq.com/protocols: "http,https,ws,wss"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
        - path: "/api/v1/accounts"
          pathType: ImplementationSpecific
          backend:
            service:
              name: account-cmd-svc
              port:
                number: 80
        - path: "/api/v1/accounts-query"
          pathType: ImplementationSpecific
          backend:
            service:
              name: account-query-svc
              port:
                number: 80
       