apiVersion: v1
kind: Service
metadata:
  name: account-cmd-svc
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: account-cmd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080